### ISSUE TITLE
Page transitions

### ISSUE THREAD

**Issue by mdings** [loteoo/hyperstatic-demo#4]
Is there a possibility currently to implement page transitions?

**Comment by loteoo** [comment]
Transitions for the next page should be doable  (fade in, slide in, etc) but transitions for the removal of the current page from the dom would require delaying the navigation. You could wrap the Link component with your own and delay the navigation, but I assume it would be pretty messy to do.

Adding official support for this would be nice to do at some point

**Comment by mdings** [comment]
Hey @loteoo,

I decided to go for a wrapper around `{Router(state)}` and have that observed by the MutationObserver.
Basically whenever Hyperstatic updates the innerHTML I intercept the changes and run an animation. After the animation is done I proceed with replacing the innerHTML. This works for me now, although I still think it might be good to have some kind of native API for this.
